### ISSUE TITLE
Events spanning multiple days are split across weeks when necessary

### ISSUE THREAD

**Issue by marapredescu1** [RinneganOrg/React-Calendar#1]
Make it happen!
- Entries across several weeks keep the same label
- Nice to have: indicate if event begins or ends outside current visible calendar

![image](https://user-images.githubusercontent.com/20516913/193267866-3d9f7100-b962-480d-b08f-c474b70e90f5.png)

**Comment by MihaelaCretu11** [comment]
Implemented
