### ISSUE TITLE
Different types of events

### ISSUE THREAD

**Issue by marapredescu1** [RinneganOrg/React-Calendar#2]
** starting hour if necessary for all events
- flat badge in muted colours for past events (multiple days)
- highlighted badge, white text and shadow for active/future events (multiple days)
- dotted text for timed events, empty dot for past and full dot for active/future (timed)

**Comment by MihaelaCretu11** [comment]
const allEvents = [
    {id: 'warning', content: 'Projects', className: 'task task--warning'},
    {id: 'danger', content: 'Design Sprint', className: 'task task--danger'},
    {id: 'primary', content: 'Product Checkup 1', className: 'task task--primary'},
  ]

**Comment by MihaelaCretu11** [comment]
Get primary and secondary colour from parent component for text/background in event, without it, will use default colours.

**Comment by MihaelaCretu11** [comment]
Colour options are not part of event types, if this will become a feature, it will be a different ticket
